### ISSUE TITLE
RFC: "@suppress" tag for suppressing individual diagnostics

### ISSUE THREAD

**Issue by octogonz** [Microsoft/tsdoc#134]
It's very useful for an API analysis tool to provide strict error checking and validation of best practices.  But we frequently receive feedback that certain checks are too strict.  For a particular project, they may be irrelevant or unhelpful.  I'd like to provide a way for people to suppress a specific instance of a validation rule.

I'm thinking we will assign a name to each diagnostic message, similar to TSLint rule names.  For example, a TSDoc error would be prefixed with `tsdoc-` like this:

```
Code: tsdoc-must-escape-gt
Message:  The ">" character should be escaped using a backslash to avoid confusion with an HTML tag
```

And for API Extractor (which uses TSDoc to parse the code comments, but then applies its own validation on top of that), the prefix would be `ae-`:

```
Code: ae-undocumented-link-target
Message: The {@link} tag references an @internal or @alpha API item, which will not appear in the generated documentation
```

In the **api-extractor.json** config file, we'll provide a way to suppress a warning for an entire project:

```
{
  . . .
  "diagnosticMessages": {
    "ae-undocumented-link-target": "disabled",
    "tsdoc-must-escape-gt": "disabled"
  }
}
```

But if you only want to suppress it for a particular instance, maybe you can do this by marking up the doc comment, like this:

```ts
/**
 * Prints a merger conflict chunk, delimited by 
 * "<<<<<<<", "======", and "<<<<<<<".
 * {@suppress tsdoc-must-escape-gt, tsdoc-must-escape-lt}
 */
export function writeMergeConflictChunk(output: Stream, diff: DiffChunk): void {
}
```

Does this feature seem useful to you?  Would you use it?

**Comment by pgonzal** [comment]
@aciccarello could you provide a little more detail?  :-P  Does the design seem misguided?  Or are you just saying that you wouldn't personally need this feature?

Is your concern mainly with the `@suppress` tag, or do you also dislike the idea of labeling each error with a name such as `ae-undocumented-link-target`?  I also considered the TypeScript compiler's approach, where diagnostics have numbers (e.g. `TS1003`).  However that seemed less readable.

**Comment by aciccarello** [comment]
@pgonzal Sure. My gut reaction is that if you frequently need to suppress parts of tsdoc, you are getting more into a docs linter. While that may be helpful when generating documentation, I don't know that it should be part of tsdoc core, especially early on. My impression is that linter rules change frequently and maintaining them in the core library could complicate things.

Coming from typedoc's loose parsing of doc comments, I don't see myself looking for this feature to be included.

**Comment by octogonz** [comment]
@aciccarello I've come around to the same viewpoint.  The most common use case for suppressions is to bulk-ignore all legacy violations, so that we can start applying the stricter rules for new changes going forward.  In this situation, tracking suppressions in source code comments is clumsy and clutters the code.  Such suppressions really need to go in a file (e.g. **suppressions.json**) that can be easily generated by a tool.

I'm going to close this RFC.
