### ISSUE TITLE
Count Us In

### ISSUE THREAD

**Issue by EisenbergEffect** [Microsoft/tsdoc#15]
Just dropping a quick note here to let the project leads know that the Aurelia team would love to support this effort and help out in any way we can. I've built our doc/site generator on TypeDoc and would love to align with this new effort. I'm working on Aurelia vNext now and I'd love to leverage TSDoc as early as possible in that process as well. Feel free to close this issue once you've let me know how we can get involved :) Thanks!

**Comment by DovydasNavickas** [comment]
@pgonzal, I see we're getting traction 😁
@EisenbergEffect, feel free to jump into discussions in other issues while we're brainstorming.

**Comment by EisenbergEffect** [comment]
Done :)

**Comment by pgonzal** [comment]
Thanks!  I've merged the PR
