### ISSUE TITLE
Support for interface properties?

### ISSUE THREAD

**Issue by fastfedora** [Microsoft/tsdoc#152]
Using the TSDoc Playground, it doesn't appear that interfaces are fully supported.

The documentation for the interface as a whole is generated, but the documentation for the properties is not, nor are they appearing in AST. Will these be supported in the future?

An example to copy & paste into the TSDoc Playground to see the issue is:  

```
/**
 * A record of some type.
 */
interface IRecord {
    /** 
     * A unique identifier
     */
    id: string;

    /** The record value */
    value: number;

    // The date this record was last updated
    lastUpdated: Date;
}
```

I searched the existing documentation and issues and couldn't find anything related to this. It looked like interfaces were being documented in this manner, but this isn't being reflected in the playground.

**Comment by octogonz** [comment]
The playground just grabs the first comment it sees and ignores the rest of the text. It's not a real documentation engine. There was another issue about this suggesting how we can make that more clear.

**Comment by octogonz** [comment]
Here it is:  https://github.com/Microsoft/tsdoc/issues/115

**Comment by fastfedora** [comment]
Thanks. I was searching for "interface" so missed this issue about types in general.

Two things might have helped me here:

1. Documentation examples in/linked from the README that show usage with different TypeScript constructs (`interface`, `type`, `class`, `enum`, etc). 

2. A note on the TSDoc playground that it's not actually parsing TypeScript, or that only the first comment is being parsed, as you stated above. So the playground is not a place to explore how more complex types would be documented.

For context, at this stage, I am merely trying to evaluate different approaches to documenting TypeScript, so I can start formatting my documentation comments correctly. I haven't installed a full documentation engine yet. 

So my use case here was to evaluate whether TSDoc is a good syntax to use, separate from any specific engine. I was using the playground as a way to experiment with support, specifically support for interface documentation, which was not obvious whether/how it was supported.

**Comment by octogonz** [comment]
> For context, at this stage, I am merely trying to evaluate different approaches to documenting
> TypeScript, so I can start formatting my documentation comments correctly. I haven't installed
> a full documentation engine yet.

BTW you might take a look at [API Extractor](https://api-extractor.com/).  Version 7 will be a major update.  You can try out the beta by doing `npm i -g @microsoft/api-extractor@beta` (or `npm i -g @microsoft/api-documenter@beta` for the documentation generator component).
