### ISSUE TITLE
[playground] Option to share a custom sample

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/tsdoc#159]
It would be useful to be able to share a link to the playground which pre-fills the input based on the URL much like how the official TypeScript playground lets you append `#src=` to a URL to set the code.

http://www.typescriptlang.org/play/index.html#src=type%20AssertTrue%3CT%20extends%20true%3E%20%3D%20T%3B%0D%0Atype%20Test%20%3D%20AssertTrue%3Cundefined%20extends%20true%20%3F%20true%20%3A%20false%3E

I think the agentcooper's share method makes more sense as it compresses the size of the url and removes potentially problematic characters.

https://typescript-play.js.org/#code/C4TwDgpgBAogjgVwIYBsA8AVANFAqgPigF4oBtDAXSggA9gIA7AEwGczcqB+dq2+5tuS5RgAJwTQAXFABmqFlNnyIAbgBQoSFACCLBaOAZxETNTqNWI44RIYVQA

**Comment by octogonz** [comment]
We started to work on this before. If I remember right there was a security concern where TSDoc can contain HTML tags which could contain executable scripts, so we would need an HTML sanitizer library. There was some trickiness about how that would interface with React, which if I remember right was somehow connected to https://github.com/Microsoft/tsdoc/issues/138

**Comment by Gerrit0** [comment]
The playground already strips HTML tags from the output and includes only their text. I tried including `<script>alert(1)</script>` and `alert(1)` was displayed. It looks like the security issue should be solved with #139

**Comment by octogonz** [comment]
> The playground already strips HTML tags from the output and includes only their text. 

It doesn't really "strip" them.  They simply aren't emitted yet (again because we realized there was a security issue).  I should finally have some time this weekend to implement the DocXmlElement thing, and then everything will be unblocked.

**Comment by octogonz** [comment]
@KevinTCoughlin FYI (who I think originally proposed the code-sharing query parameter)
