### ISSUE TITLE
Issue using TSDoc comments in .tsx files

### ISSUE THREAD

**Issue by telmotrooper** [microsoft/tsdoc#165]
I always get both `ts` and `tslint` errors when I try adding a TSDoc block comment in a .tsx file. Is it even supported to use TSDoc comments in .tsx files? I can't find anyone commenting on the issue on Google.

**Comment by octogonz** [comment]
Are you able to share a branch and some instructions for reproing these errors? I haven't seen that problem before. It might be something about your configuration.

**Comment by telmotrooper** [comment]
It was a silly mistake on my part, sorry! I'll be closing the issue.
