### ISSUE TITLE
README says "Markdown integration" but Markdown doesn't work in playground?

### ISSUE THREAD

**Issue by trusktr** [microsoft/tsdoc#167]
Maybe it isn't clear how to use Markdown, but the README says that on objective is support for Markdown, however I don't seem to be able to use it in the playground.

I do see links like `{@link core-library#Statistics | Statistics subsystem}`, but I'm not able to do `[Statistics subsystem](core-library#Statistics)`.

Can we use Markdown? Or is that a goal which is not met yet?

**Comment by Gerrit0** [comment]
You are probably looking for #70

**Comment by octogonz** [comment]
Also I recently outlined the Markdown status here: https://github.com/microsoft/tsdoc/issues/169

Please reopen if you still have questions.
