### ISSUE TITLE
New documentation generator for typescript

### ISSUE THREAD

**Issue by s-panferov** [Microsoft/tsdoc#17]
Hello! While discussing https://github.com/Microsoft/TypeScript/issues/23772 @mhegazy pointed me to your project.

I'm development a new TypeScript [documentation generator](https://github.com/s-panferov/docscript) based on the latest TypeScript and ReactJS + a central documentation portal like docs.rs. There is a lot of work should be done still, but you can take a look how it works at http://tsdoc.io/typescript/2.8.3 (yes, I accidently picked the same domain as your project name :-))

I'm not sure that we're doing the same thing here, but I'm ready to collaborate and incorporate your ideas.

**Comment by pgonzal** [comment]
Cool, thanks for your interest!  Feel free to create a PR to add yourself to the [Who's Involved](https://github.com/Microsoft/tsdoc#whos-involved-) section.
