### ISSUE TITLE
Suppress error for jsx pragma

### ISSUE THREAD

**Issue by xthilakx** [microsoft/tsdoc#213]
I have a project that uses [emotion's css prop](https://emotion.sh/docs/css-prop) and it needs to have this JSX pragma on top every file - `/** @jsx jsx */`

`eslint-plugin-tsdoc` complains about the jsx pragma
```
ESLint: tsdoc-undefined-tag: The TSDoc tag "@jsx" is not defined in this configuration(tsdoc/syntax)
```

Is there a way to continue using this plugin while configuring it to not produce errors for jsx pragma?

**Comment by joshrasmussen34** [comment]
@xthilakx I've been able to solve this by just creating a `tsdoc.json` file in the same folder as my `tsconfig.json` file with `@jsx` as a defined tag. 

https://github.com/microsoft/tsdoc/tree/master/tsdoc-config

**Comment by octogonz** [comment]
That is the intended solution. 👍
