### ISSUE TITLE
Escape @ symbol in @example code block

### ISSUE THREAD

**Issue by tristanMatthias** [microsoft/tsdoc#216]
## Problem
Currently, the `@` breaks styling if used inside the `@example+```...``` `

## Example
```ts
/**
 * GraphQL JSON type
 *
 * @example
 * ```ts
 *  import { Field, InputType } from 'type-graphql';
 *  import API from '@brix/api';
 *
 *  @InputType()
 *  export class EExampleInput {
 *    @Field(() => String)
 *    type: string;
 *
 *    @Field(() => API.GraphQLJSON)
 *    data: Object;
 *  }
 * ```
 */
```

Here the `@brix/api` breaks, and also the decorators

Example VSCode hover preview:

![image](https://user-images.githubusercontent.com/2550138/74403102-22d58900-4df4-11ea-984f-c3783925a9fe.png)

**Comment by brokenmass** [comment]
Can anyone look into this issue ?

**Comment by octogonz** [comment]
I just pasted this code sample into the [TSDoc Playground](https://microsoft.github.io/tsdoc/) and it renders correctly.

> Example VSCode hover preview:

As far as I know, VS Code's syntax highlighter does not use the `@microsoft/tsdoc` reference parser. Thus it would need to be fixed on their end.  There's not much the TSDoc can do.

The GitHub project for VS Code is here: https://github.com/microsoft/vscode
