### ISSUE TITLE
Can we have rust-like three slashes for quick docs?

### ISSUE THREAD

**Issue by alshdavid** [microsoft/tsdoc#226]
For objects that need a lot of short documentation, TSDoc can be quite verbose, requiring 3 lines of code for one line of comment.

The triple slash style gives a great short-hand alternative to write notes

```typescript
/// foo makes bars
function foo() {
  return 'bar'
}
```

**Comment by Gerrit0** [comment]
#160

**Comment by octogonz** [comment]
Closing since this is a duplicate of https://github.com/microsoft/tsdoc/issues/160
