### ISSUE TITLE
Unable to parse module specifier: `export * as X`

### ISSUE THREAD

**Issue by MichaelHirn** [microsoft/tsdoc#239]
Pretty much regardless of configuration (tsconfig or api-extractor.json) `api-extractor` throws an error (`Unable to parse module specifier`) when it encounters:

```typescript
export * as SomeName from './someFile'
```

the following works correctly

```typescript
export * from './someFile'
export { Something1, Something2 } from './someFile'
```

I'm new to TS but I feel `export * as SomeName` has real world benefits so should be supported?

**Comment by octogonz** [comment]
This is the GitHub repo for TSDoc. 

API Extractor's issues are tracked here: https://github.com/microsoft/rushstack/

Your specific issue seems to be a dupe of https://github.com/microsoft/rushstack/issues/1866
