### ISSUE TITLE
build fail for tsdoc

### ISSUE THREAD

**Issue by yuzhidi** [microsoft/tsdoc#243]
Hi,
I followed Contributing.md but build fail
I have no idea to handle this,
is there any suggestion? thx.

$ npm run build

> @microsoft/tsdoc@0.12.20 build D:\study\tsdoc\tsdoc
> node ./build.js

-- TYPESCRIPT --

node_modules/jest-diff/build/diffLines.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DiffOptions } from './types';
              ~

node_modules/jest-diff/build/diffLines.d.ts:8:34 - error TS1005: ';' expected.

8 import type { DiffOptions } from './types';
                                   ~~~~~~~~~

node_modules/jest-diff/build/index.d.ts:10:13 - error TS1005: '=' expected.

10 import type { DiffOptions } from './types';
               ~

node_modules/jest-diff/build/index.d.ts:10:34 - error TS1005: ';' expected.

10 import type { DiffOptions } from './types';
                                    ~~~~~~~~~

node_modules/jest-diff/build/index.d.ts:11:1 - error TS1128: Declaration or statement expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
   ~~~~~~

node_modules/jest-diff/build/index.d.ts:11:13 - error TS1005: ';' expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
               ~

node_modules/jest-diff/build/index.d.ts:11:52 - error TS1005: ';' expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
                                                      ~~~~~~~~~

node_modules/jest-diff/build/printDiffs.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DiffOptions, DiffOptionsNormalized } from './types';
              ~

node_modules/jest-diff/build/printDiffs.d.ts:8:57 - error TS1005: ';' expected.

8 import type { DiffOptions, DiffOptionsNormalized } from './types';
                                                          ~~~~~~~~~


Found 9 errors.

ERROR: Command failed: D:\study\tsdoc\tsdoc\node_modules\.bin\tsc
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @microsoft/tsdoc@0.12.20 build: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @microsoft/tsdoc@0.12.20 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-15T09_46_28_284Z-debug.log

**Comment by octogonz** [comment]
I see, you are using the "standalone with NPM" instructions from [Contributing.md](https://github.com/microsoft/tsdoc/blob/master/Contributing.md).

For now, try using the Rush instructions instead:
```shell
$ cd ./tsdoc
$ rush install
$ rush build
```
