### ISSUE TITLE
TypeError: parse is not a function

### ISSUE THREAD

**Issue by theADAMJR** [microsoft/tsdoc#264]
```node
npm i -D @microsoft/tsdoc
tsdoc -i
tsdoc
```
Then changing `tsdoc.markdown.parser = "typescript"`

Throws:
```
exec error: Error: Command failed: jsdoc /Users/adamj/Documents/Projects/Code/2pg-music/src/ -c C:\Users\adamj\Documents\Projects\Code\2pg-music\tsdoc.json -d /Users/adamj/Documents/Projects/Code/2pg-music/docs README.md
ERROR: Unrecognized Markdown parser "undefined". Markdown support is disabled.
C:\Users\adamj\AppData\Roaming\npm\node_modules\jsdoc\lib\jsdoc\readme.js:20
        this.html = parse(content);
                    ^

TypeError: parse is not a function
```

It also does not work with markdown parsers: "gfm", "flow", "typescript".

**Repo**: https://github.com/theADAMJR/2PG-Music

**Comment by octogonz** [comment]
@theADAMJR It appears that you were intending to use the [TSDoc#](https://www.npmjs.com/package/tsdoc) package.  Its name is similar to [@microsoft/tsdoc](https://www.npmjs.com/package/@microsoft/tsdoc), but they are different and unrelated projects.  As far as I understood, TSDoc# was [abandoned a long time ago](https://github.com/xperiments/TSDoc/issues/19); it hasn't been updated in 7 years.

**Comment by octogonz** [comment]
(I am closing this issue -- please reply or reopen if I misunderstood something. Thanks!)
