### ISSUE TITLE
Cannot build api-demo folder

### ISSUE THREAD

**Issue by radonirinamaminiaina** [microsoft/tsdoc#265]
I followed the tutorial in folder /api-demo. 
And when I try to build it, I have the error below:
```
Project: api-demo@0.1.0
Heft version: 0.13.9
Node version: v14.7.0

Error: Cannot read config file: my_path\tsdoc\api-demo\.eslintrc.js
Error: Failed to patch ESLint because the calling module was not recognized
```
System: Win 10

**Comment by octogonz** [comment]
I was able to confirm this problem. But it only happens if you follow the README instructions using `npm install --no-package-lock`.  

Whereas if you follow the instructions using `rush install` then it works correctly.

**Comment by octogonz** [comment]
Looks like the problem is that [@rushstack/eslint-patch](https://www.npmjs.com/package/@rushstack/eslint-patch) needs to be upgraded for compatibility with the latest ESLint:

[eslint-patch/CHANGELOG.md](https://github.com/microsoft/rushstack/blob/master/stack/eslint-patch/CHANGELOG.md)
> # Change Log - @rushstack/eslint-patch
> 
> This log was last generated on Fri, 30 Oct 2020 00:10:14 GMT and should not be manually modified.
> 
> ## 1.0.6
> Fri, 30 Oct 2020 00:10:14 GMT
> 
> ### Patches
> 
> - Update the "modern-module-resolution" patch to support ESLint 7.8.0 and newer
> 
> ## 1.0.5
> Wed, 30 Sep 2020 18:39:17 GMT

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/tsdoc/pull/266
