### ISSUE TITLE
Request: Document interfaces

### ISSUE THREAD

**Issue by KyleTryon** [microsoft/tsdoc#287]
I am hoping to document interfaces so that all methods have their parameters linked and documented.
I am surprised to not see this and am wondering if maybe I have simply not found the option. 

Example:
![image](https://user-images.githubusercontent.com/33272306/113013999-3784f580-914a-11eb-8dff-ffb36a38ae44.png)

---
## constructor

+ new Run(parameters: RunParameters): Run

### Parameters

**parameters:**  _RunParameters_

---

I have included docs comments for the interface that is referenced in this example but it seems from here the user can not easily see from the docs what parameter values will be required. There is no link to any kind of interface object definition.

Looking to PhaserJS as an example:
https://photonstorm.github.io/phaser3-docs/Phaser.Types.Core.html#toc2__anchor

They are using JSDoc and it appears that their TypeDefinitions are being picked up and displayed here on this page.

## Ask

Document interfaces as linkable objects from where they are called (methods, constructors, ect)

**Comment by Gerrit0** [comment]
I suggest moving this issue to https://github.com/TypeStrong/typedoc/issues, as TSDoc is a doc comment standard proposal - and not what's causing the result that you're looking at.

TypeDoc will only document what you export from your entry points. `RunParameters` isn't exported, and therefore isn't documented. If you export it, then TypeDoc will create a link from your parameter type to the interface.
