### ISSUE TITLE
ESlint plugin: The TSDoc tag "@notExported" is not recognized

### ISSUE THREAD

**Issue by crystalfp** [microsoft/tsdoc#298]
I have installed TypeDoc and its plugin  `typedoc-plugin-not-exported` that adds a new tag `@notExported`.
Running ESlint with `eslint-plugin-tsdoc` rightly complains that `@notExported` tag is not defined:
`tsdoc-undefined-tag: The TSDoc tag "@notExported" is not defined in this configuration (tsdoc/syntax)`
Is there any mechanism to make the `eslint-plugin-tsdoc` ignore this or generally a set of tags?
Thanks!
mario

**Comment by AlexRogalskiy** [comment]
You should add **tsdoc.json** file to the directory that contains **tsconfig.json** file.
Inside "tsdoc.json" file you should add the following json document with corresponding tag name **@notExported**:

{
    "$schema": "https://developer.microsoft.com/json-schemas/tsdoc/v0/tsdoc.schema.json",
    "tagDefinitions": [
        {
            "tagName": "@author",
            "syntaxKind": "block"
        },
        {
            "tagName": "@description",
            "syntaxKind": "block"
        },
        {
            "tagName": "@implements",
            "syntaxKind": "modifier"
        }
    ]
}

**Comment by crystalfp** [comment]
Yes, this solved the problem of not recognized tags, but now `eslint-plugin-tsdoc` complains that  `tsdoc-unsupported-tag: The TSDoc tag "@param" is not supported by this tool (tsdoc/syntax) at ...` idem for `tsdoc-unsupported-tag: The TSDoc tag "@returns" is not supported by this tool (tsdoc/syntax)`. But if I add `@returns` to `tsdoc.json` it complains that the tag is already defined.
So really don't know how to use effectively this plugin.
Thanks for looking!
mario

**Comment by crystalfp** [comment]
Solved. you need to add `"@param": true, "@returns": true` to the `"supportForTags"` section of the configuration file `tsdoc.json`.
Anyway, this sounds like a bug to me.
