### ISSUE TITLE
Deprecate and remove @override

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/tsdoc#322]
[TypeScript 4.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag) introduced the `override` keyword, which appears to have the same semantics as this tag, with the benefit of being directly recognized by the language. As such, for recent TS versions this tag is potential for confusion. It should either be deprecated / removed, or it's documentation updated to clarify why it exists alongside the keyword and when it should be used instead/in addition to the keyword.

**Comment by zelliott** [comment]
The `override` keyword isn't present in the `.d.ts` (https://github.com/microsoft/TypeScript/issues/2000#issuecomment-813527475) and API Extractor runs on `.d.ts`. This should be mentioned in the documentation at https://tsdoc.org/pages/tags/override/. Thoughts @octogonz?

**Comment by SmashingQuasar** [comment]
I second @Gerrit0's issue regarding this tag. It should be deprecated.
However, is TSDoc handling the native `override` keyword?
