### ISSUE TITLE
The "advanced" api-demo scenario does not collect all TypeScript comments

### ISSUE THREAD

**Issue by pgonzal** [Microsoft/tsdoc#56]
@Gerrit0 commented in https://github.com/Microsoft/tsdoc/pull/55#discussion_r214234849 that the [walkCompilerAstAndFindComments()](https://github.com/Microsoft/tsdoc/blob/281213828f668f98db51e06d023335161b3aa5b2/api-demo/src/advancedDemo.ts#L66) function does not find some comments.

We should find a better example of how to do this.  @eps1lon suggested:
> You could use the `checker` to get the symbol of a node. Symbols have a method `getDocumentationComment`. Never used this method. The name just sounds fitting.

@sandersn / @DanielRosenwasser could you provide some guidance?

**Comment by sandersn** [comment]
Quick on-the-bus question: have you tried ts.getJSDocTags(node: Node)? That only returns jsdoc  of course, and it chops everything up into tags, but it might be enough. 

I’ll take a closer look when I’m back in the office after the holiday.

**Comment by pgonzal** [comment]
@sandersn I don't think ` ts.getJSDocTags(node: Node)` will work.  It attempts to parse the code comment (using a non-TSDoc compliant parser).  Whereas for the purposes of this demo, we want to extract the `/** ... */` text range to be processed the TSDoc parser.

**Comment by Gerrit0** [comment]
I've been looking into this a bit more and noticed the `ts.getCommentRange` method, which might meet the requirements.

**Comment by pgonzal** [comment]
I tried `ts.getCommentRange()` but it returns a nonempty range for most AST nodes, which includes code expressions.  The docs suggest that this function is meant to be used when injecting comments in emitted output.

So we still don't have an answer:  What's a good way to scan a source file and find all the `/** */` comment ranges?  @RyanCavanaugh

**Comment by pgonzal** [comment]
@eps1lon thanks for contributing this PR.  Today I'm going to look at the various options and see what's the best approach for this demo.

**Comment by pgonzal** [comment]
After debugging into the compiler library, I realized that [advancedDemo.ts#L69](https://github.com/Microsoft/tsdoc/blob/281213828f668f98db51e06d023335161b3aa5b2/api-demo/src/advancedDemo.ts#L69) was calling `SourceFile.getText()` instead of `SourceFile.getFullText()`.  This sometimes some leading comments/whitespace, which shifted the buffer indexes around, producing mostly correct but sometimes very bizarre results.  After fixing that, things got a lot more sane.

Although `tsutils.forEachComment()` is a pretty good way to enumerate all comments associated with a subtree, I'm not sure it's best for this demo.  The demo is meant to model a tool that discovers declarations and then parses the TSDoc that would conventionally be associated with a declaration.  We probably would not want to exhaustively consider every comment in the input.  Also we should ignore `//` and `/* */` style comments.  The compiler's internal [ts.getJSDocCommentRanges()](https://github.com/Microsoft/TypeScript/blob/262ea5b06ee22e4e79d11f66f84c09775808a0f2/src/compiler/utilities.ts#L954) seems like a closer match for what we need.

However, with this approach we sometimes pickup duplicates when iterating the AST tree.  For example when analyzing "`public static example(): void {`" and calling `ts.getJSDocCommentRanges()`, it will find the same comment for both the `PublicKeyword` node and the `MethodDeclaration` node (since they have the same physical position).  We need to filter out the "insignificant" nodes.  @RyanCavanaugh pointed me to `ts.isDeclaration()` which should work, however that is an unfortunately internal API.

I'll see if I can combine all these ideas together into a PR.

**Comment by pgonzal** [comment]
This was fixed in PR #59.
