### ISSUE TITLE
Repo is unlicensed

### ISSUE THREAD

**Issue by strugee** [Microsoft/tsdoc#77]
Pretty much what the title says; the repo has no `LICENSE` or `COPYING` file and the README doesn't say anything about it either, from a quick skim.

**Comment by pgonzal** [comment]
We don't publish the root of the repo.  The LICENSE is in the https://github.com/Microsoft/tsdoc/tree/master/tsdoc folder which we do publish.

I suppose we could also add some files at the repo root to make GitHub's heuristics happy. :-)

**Comment by pgonzal** [comment]
Resolved.
